In [1]:
import numpy as np

In [3]:
from sklearn.preprocessing import MinMaxScaler

In [4]:
data = np.random.randint(0, 100, (10, 2))

In [5]:
data

array([[85, 68],
       [41, 41],
       [ 0, 71],
       [84, 11],
       [20, 48],
       [98, 48],
       [28, 55],
       [67, 64],
       [97, 83],
       [12, 91]])

scale all the data

scale_model is an instance of MinMaxScaler()

In [6]:
scaler_model = MinMaxScaler()

In [7]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

!!! no need to care about warning

just convert int32 to float64

In [8]:
scaler_model.fit(data)

/Users/lichenglong/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)

MinMaxScaler(copy=True, feature_range=(0, 1))

transform the data: divide all the data by the max value (98)

In [9]:
scaler_model.transform(data)

array([[ 0.86734694,  0.7125    ],
       [ 0.41836735,  0.375     ],
       [ 0.        ,  0.75      ],
       [ 0.85714286,  0.        ],
       [ 0.20408163,  0.4625    ],
       [ 1.        ,  0.4625    ],
       [ 0.28571429,  0.55      ],
       [ 0.68367347,  0.6625    ],
       [ 0.98979592,  0.9       ],
       [ 0.12244898,  1.        ]])

always, we fit the training data, but we transform both the training and the test data.

If you want to fit and transform the training at the same time. use fit_transform()

In [10]:
scaler_model.fit_transform(data)

/Users/lichenglong/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)

array([[ 0.86734694,  0.7125    ],
       [ 0.41836735,  0.375     ],
       [ 0.        ,  0.75      ],
       [ 0.85714286,  0.        ],
       [ 0.20408163,  0.4625    ],
       [ 1.        ,  0.4625    ],
       [ 0.28571429,  0.55      ],
       [ 0.68367347,  0.6625    ],
       [ 0.98979592,  0.9       ],
       [ 0.12244898,  1.        ]])

split the data

In [11]:
import pandas as pd

In [12]:
mydata = np.random.randint(0, 100, (50, 4))

In [13]:
mydata

array([[40, 34, 91, 29],
       [33, 84, 44, 68],
       [13, 13, 14, 81],
       [24, 12, 53, 33],
       [54, 90, 26, 53],
       [29, 82, 74, 35],
       [61, 99, 53, 40],
       [87, 88, 82, 65],
       [19, 32, 31, 31],
       [38, 88, 92, 81],
       [41, 36, 32, 20],
       [38, 92, 89, 57],
       [40, 69, 28, 69],
       [59, 50, 85, 33],
       [93, 71,  1, 29],
       [35, 21, 47, 45],
       [70, 72, 95, 24],
       [58, 92, 46, 16],
       [ 9, 77, 56, 52],
       [ 8,  4, 76, 98],
       [96, 62, 64, 87],
       [94, 10,  4, 50],
       [70, 47, 69, 59],
       [32, 23,  8, 62],
       [46, 11, 85, 73],
       [21, 63, 17, 30],
       [66, 53, 88, 22],
       [46, 29, 96, 61],
       [42, 68, 46,  7],
       [52, 31, 14, 38],
       [95, 35, 83,  9],
       [46, 12, 91,  9],
       [42, 27, 30, 73],
       [ 8, 31, 88, 27],
       [92, 85, 37, 15],
       [83, 35, 80,  4],
       [22, 56, 69, 31],
       [88, 86, 91, 41],
       [70, 44, 67, 57],
       [52, 37, 12, 74],
       [54, 39, 96, 12],
       [57,  0, 31, 40],
       [67, 73, 39, 33],
       [78, 32, 86, 75],
       [ 6,  2, 36, 11],
       [80, 54, 16, 99],
       [95, 98, 59, 96],
       [35, 47,  3, 80],
       [92, 79, 80, 74],
       [15,  3, 23, 66]])

In [15]:
df = pd.DataFrame(data = mydata)

default column name: 0 1 2 ...

In [16]:
df

     0   1   2   3
0   40  34  91  29
1   33  84  44  68
2   13  13  14  81
3   24  12  53  33
4   54  90  26  53
5   29  82  74  35
6   61  99  53  40
7   87  88  82  65
8   19  32  31  31
9   38  88  92  81
10  41  36  32  20
11  38  92  89  57
12  40  69  28  69
13  59  50  85  33
14  93  71   1  29
15  35  21  47  45
16  70  72  95  24
17  58  92  46  16
18   9  77  56  52
19   8   4  76  98
20  96  62  64  87
21  94  10   4  50
22  70  47  69  59
23  32  23   8  62
24  46  11  85  73
25  21  63  17  30
26  66  53  88  22
27  46  29  96  61
28  42  68  46   7
29  52  31  14  38
30  95  35  83   9
31  46  12  91   9
32  42  27  30  73
33   8  31  88  27
34  92  85  37  15
35  83  35  80   4
36  22  56  69  31
37  88  86  91  41
38  70  44  67  57
39  52  37  12  74
40  54  39  96  12
41  57   0  31  40
42  67  73  39  33
43  78  32  86  75
44   6   2  36  11
45  80  54  16  99
46  95  98  59  96
47  35  47   3  80
48  92  79  80  74
49  15   3  23  66

In [18]:
df = pd.DataFrame(data=mydata, columns = ['f1', 'f2', 'f3', 'label'])

In [19]:
df

    f1  f2  f3  label
0   40  34  91     29
1   33  84  44     68
2   13  13  14     81
3   24  12  53     33
4   54  90  26     53
5   29  82  74     35
6   61  99  53     40
7   87  88  82     65
8   19  32  31     31
9   38  88  92     81
10  41  36  32     20
11  38  92  89     57
12  40  69  28     69
13  59  50  85     33
14  93  71   1     29
15  35  21  47     45
16  70  72  95     24
17  58  92  46     16
18   9  77  56     52
19   8   4  76     98
20  96  62  64     87
21  94  10   4     50
22  70  47  69     59
23  32  23   8     62
24  46  11  85     73
25  21  63  17     30
26  66  53  88     22
27  46  29  96     61
28  42  68  46      7
29  52  31  14     38
30  95  35  83      9
31  46  12  91      9
32  42  27  30     73
33   8  31  88     27
34  92  85  37     15
35  83  35  80      4
36  22  56  69     31
37  88  86  91     41
38  70  44  67     57
39  52  37  12     74
40  54  39  96     12
41  57   0  31     40
42  67  73  39     33
43  78  32  86     75
44   6   2  36     11
45  80  54  16     99
46  95  98  59     96
47  35  47   3     80
48  92  79  80     74
49  15   3  23     66

In [20]:
X = df[['f1', 'f2', 'f3']]

In [21]:
y = df['label']

In [22]:
from sklearn.model_selection import train_test_split

train : test = 7 : 3, random_state is just random seed

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [24]:
X_train.shape

(35, 3)

In [25]:
X_test.shape

(15, 3)